### ISSUE TITLE
Provider doesn't support next types of components: Database, File share, Firewall, Load balancer, Network zone, Server

### ISSUE THREAD

**Issue by ankek** [mories76/terraform-provider-ardoq#118]
Hi there,
First at all, many thanks for your TF provider.

The problem:
As of now, ardoq provider supports only "component" as type of resource.
Could you please add support for missed types like Database, File share, Firewall, Load balancer, Network zone, Server?

See screenshot

![Screenshot 2023-09-04 142006](https://github.com/mories76/terraform-provider-ardoq/assets/36890976/c5fb1790-19a8-455c-bd46-1f26ddd7de86)

**Comment by mories76** [comment]
Hi,

Thanks for taking a look at my terraform provider.
I must warn you in advance. This project had been dormant for a long time. I don't know of anyone using this provider.

But..
You mention that this provider one supports "component" as type of resource. But that's is not how Ardor works.
In Ardoq you only have components and relations, roughly.
From your example image, COMPONENT, Database etc. are all component of a certain type which is dictated in the model.

I would suggest you create some object (components) in a workspace and query them with terraform using the examples as documented. For example https://registry.terraform.io/providers/mories76/ardoq/latest/docs/data-sources/components

You will get a result for all components In a specific workspace with their associated attributes.
I hope this will get you up and running.
