### ISSUE TITLE
error:  request details for a workspace with the name "Some workspace"

### ISSUE THREAD

**Issue by dilbertside** [mories76/terraform-provider-ardoq#19]
Hello,

I met an error querying a specific workspace in my organization while usin the following code:
```
# request details for a workspace with the name "Some workspace"
data "ardoq_workspace" "blah" {
    name = "Blah - Blah 2.0"
}
output "workspace_output" {
  value = data.ardoq_workspace.blah
}
```
Error: ardoq error: 
│ statuscode :404
│ Resource not found. <nil>
│ 
│   with data.ardoq_workspace.blah,
│   on ardoq.tf line 14, in data "ardoq_workspace" "blah":
│   14: data "ardoq_workspace" "blah" {
│ 

I know the workspace exists in my organization even if I cannot share here for confidential reasons..

Thank you to have a look at it!

**Comment by dilbertside** [comment]
because of this error I cannot query the following
```
# returns all components in workspace
data "ardoq_components" "all" {
  # use the retrieved data from above
  root_workspace = data.ardoq_workspace.blah.id
}
```

**Comment by mories76** [comment]
Ok, so do you think this issue is related to issue #18 ?

The provider reports a 404, I might be that I have an error handling issue.
I have some ideas on how to reproduce this, but it will be tomorrow.

**Comment by dilbertside** [comment]
It might be possible they are related.
It happened in different steps of my test of the provider and this bug block other data block which reference `root_workspace`
Usage wants we don't mix 2 bug reports in one having no way to confirm as a reporter it might be the case.

**Comment by dilbertside** [comment]
I made a mistake when I used the `ardoq_workspace`, I set the **folder name** instead of the **workspace name**.
![ardoq-workspace](https://user-images.githubusercontent.com/2637724/128280792-f02a3e00-6c7a-48a3-953e-7c77fba3b6f1.png)


I fixed that configuration error, and it was still failing for some workspace yesterday, but now with 0.1.1 version, it looks OK.

Thank you for the fix.
